- name: Create directory to store persistent journal
  file:
    path: /var/log/journal
    state: directory
  register: create_directory

- name: Setup journal directory
  command: systemd-tmpfiles --create --prefix /var/log/journal
  when: create_directory.changed

- name: Trigger Flushing of Journal to Persistent Storage
  command: systemctl start systemd-journal-flush
  # starting one-shot services is not an idempotent operation
  args:
    warn: no
  when: create_directory.changed

- name: Add users to group for reading the system journal
  user:
    name: "{{ item }}"

    append: yes
    groups: systemd-journal
  with_items: "{{ systemd_journal__users }}"

# If a distro didn't set up the journal by default,
# it almost certainly set up a traditional syslog daemon instead.
#
- name: Query - is rsyslog daemon installed?
  # Get the list of services, and look for "rsyslog".
  # Make sure to detect errors.
  shell: |
    set -o errexit -o pipefail
    (systemctl list-unit-files rsyslog.service || exit 2) | grep ^rsyslog.service
  args:
    executable: /bin/bash
  register: rsyslog_service_exists
  failed_when: rsyslog_service_exists.rc not in [0, 1]
  check_mode: False
  changed_when: False

- name: Disable syslog daemon rsyslog
  systemd:
    name: rsyslog
    enabled: no
    state: stopped
  when: systemd_journal__disable_syslog_daemon and rsyslog_service_exists.rc == 0
